#!/usr/bin/env python3
"""
RedditHarbor Opportunity Dashboard

Interactive dashboard showing AI-powered app opportunities from Reddit data.
"""

import os

import marimo as mo

from supabase import create_client

# Initialize Supabase client
supabase = create_client(
    os.getenv('SUPABASE_URL'),
    os.getenv('SUPABASE_KEY')
)

app = mo.App()

# Cell 1: Setup and Header
@app.cell
def _():
    mo.md("# 🎯 RedditHarbor - App Opportunity Discovery")
    return

# Cell 2: Description
@app.cell
def _():
    mo.md("""
    ## AI-Powered App Ideas from Reddit

    This dashboard displays app development opportunities identified through:
    1. Reddit data collection from high-signal subreddits
    2. AI analysis using Claude Haiku via OpenRouter
    3. Multi-dimensional scoring (Market, Pain, Monetization, Feasibility)

    **Showing opportunities with score >= 40.0**
    """)
    return

# Cell 3: Fetch and process data
@app.cell
def _():
    # Fetch opportunities from workflow_results table
    result = supabase.table('workflow_results').select(
        'opportunity_id, final_score, problem_description, app_concept, function_list, target_user, monetization_model'
    ).gte('final_score', 40.0).order('final_score', desc=True).limit(20).execute()

    data = result.data if result.data else []
    return (data,)

# Cell 4: Display opportunities table
@app.cell
def _(data):
    if not data:
        mo.md("No opportunities found with score >= 40.0")
    else:
        # Convert to display format
        display_data = []
        for opp in data:
            functions = opp.get('function_list', [])
            if isinstance(functions, str):
                try:
                    functions = eval(functions)
                except:
                    functions = [str(functions)]

            display_data.append({
                'Score': f"{opp.get('final_score', 0):.1f}",
                'Problem': opp.get('problem_description', 'N/A')[:70] + "...",
                'App Concept': opp.get('app_concept', 'N/A')[:70] + "...",
                'Target': opp.get('target_user', 'N/A')[:40],
                'Functions': f"{len(functions) if isinstance(functions, list) else 1}"
            })

        mo.ui.table(display_data, label=f"Top {len(display_data)} Opportunities")
    return

# Cell 5: Summary statistics
@app.cell
def _(data):
    total = len(data)
    avg_score = sum(opp.get('final_score', 0) for opp in data) / total if total > 0 else 0
    high_score_count = len([o for o in data if o.get('final_score', 0) >= 45])

    mo.md(f"""
    ## Summary Statistics

    - **Total Opportunities:** {total}
    - **Average Score:** {avg_score:.1f}
    - **High-Score (≥45):** {high_score_count}
    - **Cost per Opportunity:** ~$0.001 (Claude Haiku via OpenRouter)
    """)
    return

# Cell 6: Footer
@app.cell
def _():
    mo.md("---")
    mo.md("*Generated by RedditHarbor - AI-Powered App Discovery*")
    return

if __name__ == "__main__":
    app.run()
