#!/usr/bin/env python3
"""
Simple RedditHarbor Opportunity Dashboard

Interactive dashboard showing AI-powered app opportunities from Reddit data.
Displays opportunities with final scores >= 40.0
"""

import os

import marimo as mo

from supabase import create_client

# Initialize Supabase client
supabase = create_client(
    os.getenv('SUPABASE_URL'),
    os.getenv('SUPABASE_KEY')
)

# Fetch opportunities data
def get_opportunities(min_score: float = 40.0):
    """Fetch opportunities with score >= min_score"""
    result = supabase.table('workflow_results').select(
        'opportunity_id, final_score, problem_description, app_concept, function_list, target_user, monetization_model'
    ).gte('final_score', min_score).order('final_score', desc=True).execute()
    return result.data

# Main dashboard
app = mo.App(title="RedditHarbor - App Opportunities Dashboard")

@app.cell
def header():
    return mo.md("# 🎯 RedditHarbor - App Opportunity Discovery")

@app.cell
def description():
    return mo.md("""
    ## AI-Powered App Ideas from Reddit

    This dashboard displays app development opportunities identified through:
    1. Reddit data collection from high-signal subreddits
    2. AI analysis using Claude Haiku via OpenRouter
    3. Multi-dimensional scoring (Market, Pain, Monetization, Feasibility)

    **Showing opportunities with score >= 40.0**
    """)

@app.cell
def controls():
    # Simple controls
    return mo.md("---")

@app.cell
def opportunities_table():
    # Fetch and display opportunities
    data = get_opportunities(40.0)

    if not data:
        return mo.md("No opportunities found with score >= 40.0")

    # Convert to display format
    display_data = []
    for opp in data:
        functions = opp.get('function_list', [])
        if isinstance(functions, str):
            try:
                functions = eval(functions)
            except:
                functions = [functions]

        display_data.append({
            'Score': f"{opp.get('final_score', 0):.1f}",
            'Problem': opp.get('problem_description', 'N/A')[:100] + "...",
            'App Concept': opp.get('app_concept', 'N/A')[:100] + "...",
            'Target User': opp.get('target_user', 'N/A')[:50],
            'Functions': f"{len(functions)} functions"
        })

    return mo.ui.table(
        display_data,
        label=f"Top {len(display_data)} App Opportunities",
        show_row_numbers=True
    )

@app.cell
def stats():
    data = get_opportunities(40.0)
    total = len(data)
    avg_score = sum(opp.get('final_score', 0) for opp in data) / total if total > 0 else 0
    high_score_count = len([o for o in data if o.get('final_score', 0) >= 45])

    return mo.md(f"""
    ## Summary

    - **Total Opportunities:** {total}
    - **Average Score:** {avg_score:.1f}
    - **High-Score (≥45):** {high_score_count}
    - **Score Range:** {min(o.get('final_score', 0) for o in data) if data else 0:.1f} - {max(o.get('final_score', 0) for o in data) if data else 0:.1f}
    """)

@app.cell
def footer():
    return mo.md("---")
    return mo.md("Generated by RedditHarbor - AI-Powered App Discovery")

if __name__ == "__main__":
    app.run()
