-- Add missing LLM profiler columns to app_opportunities table
-- Required for clean pipeline integration with fixed LLM profiler

-- Add missing LLM profiler columns
ALTER TABLE app_opportunities
ADD COLUMN IF NOT EXISTS app_name TEXT,
ADD COLUMN IF NOT EXISTS final_score DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS reddit_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'discovered',
ADD COLUMN IF NOT EXISTS value_proposition TEXT;

-- Fix submission_id data type (Reddit IDs are strings, not UUIDs)
ALTER TABLE app_opportunities ALTER COLUMN submission_id TYPE TEXT USING submission_id::TEXT;

-- Add unique constraint for UPSERT operations
ALTER TABLE app_opportunities ADD CONSTRAINT unique_submission_id UNIQUE (submission_id);

-- Add comments for documentation
COMMENT ON COLUMN app_opportunities.app_name IS 'App name generated by LLM profiler (1-3 words, catchy name)';
COMMENT ON COLUMN app_opportunities.final_score IS 'Final opportunity score (0-100) generated by LLM profiler based on market potential';
COMMENT ON COLUMN app_opportunities.created_at IS 'Timestamp when the AI profile was generated';
COMMENT ON COLUMN app_opportunities.reddit_score IS 'Total Reddit engagement signals (upvotes + comments) for validation';
COMMENT ON COLUMN app_opportunities.status IS 'Processing status: discovered, analyzed, validated, etc.';
COMMENT ON COLUMN app_opportunities.value_proposition IS 'Why users need this, what benefit they get (generated by LLM)';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_app_opportunities_final_score ON app_opportunities(final_score);
CREATE INDEX IF NOT EXISTS idx_app_opportunities_app_name ON app_opportunities(app_name);
CREATE INDEX IF NOT EXISTS idx_app_opportunities_reddit_score ON app_opportunities(reddit_score);
CREATE INDEX IF NOT EXISTS idx_app_opportunities_status ON app_opportunities(status);